// <auto-generated />
using System;
using AppForSEII2526.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppForSEII2526.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppForSEII2526.API.Models.AlquilarItem", b =>
                {
                    b.Property<int>("HerramientaId")
                        .HasColumnType("int");

                    b.Property<int>("AlquilerId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("HerramientaId", "AlquilerId");

                    b.HasIndex("AlquilerId");

                    b.ToTable("AlquilarItem");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Alquiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<double>("PrecioTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Alquiler");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precioTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.CompraItem", b =>
                {
                    b.Property<int>("IdHerramienta")
                        .HasColumnType("int");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HerramientaId")
                        .HasColumnType("int");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.HasKey("IdHerramienta", "IdCompra");

                    b.HasIndex("CompraId");

                    b.HasIndex("HerramientaId");

                    b.ToTable("CompraItem");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Fabricante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Fabricante");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Herramienta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fabricanteid")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<int>("TiempoReparacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Fabricanteid");

                    b.ToTable("Herramienta");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("fechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaOferta")
                        .HasColumnType("datetime2");

                    b.Property<int>("metodoPago")
                        .HasColumnType("int");

                    b.Property<int>("paraSocio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Oferta");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.OfertaItem", b =>
                {
                    b.Property<int>("idHerramienta")
                        .HasColumnType("int");

                    b.Property<int>("idOferta")
                        .HasColumnType("int");

                    b.Property<int>("herramientaId")
                        .HasColumnType("int");

                    b.Property<int>("ofertaId")
                        .HasColumnType("int");

                    b.Property<decimal>("porcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("precioFinal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idHerramienta", "idOferta");

                    b.HasIndex("herramientaId");

                    b.HasIndex("ofertaId");

                    b.ToTable("OfertaItem");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Reparacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecogida")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrecioTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Reparacion");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.ReparacionItem", b =>
                {
                    b.Property<int>("idHerramienta")
                        .HasColumnType("int");

                    b.Property<int>("idReparacion")
                        .HasColumnType("int");

                    b.Property<int>("HerramientaId")
                        .HasColumnType("int");

                    b.Property<int>("ReparacionId")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("precio")
                        .HasColumnType("real");

                    b.HasKey("idHerramienta", "idReparacion");

                    b.HasIndex("HerramientaId");

                    b.HasIndex("ReparacionId");

                    b.ToTable("ReparacionItem");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.AlquilarItem", b =>
                {
                    b.HasOne("AppForSEII2526.API.Models.Alquiler", "Alquiler")
                        .WithMany("AlquilarItems")
                        .HasForeignKey("AlquilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppForSEII2526.API.Models.Herramienta", "Herramienta")
                        .WithMany("AlquilarItems")
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alquiler");

                    b.Navigation("Herramienta");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.CompraItem", b =>
                {
                    b.HasOne("AppForSEII2526.API.Models.Compra", "Compra")
                        .WithMany("CompraItems")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppForSEII2526.API.Models.Herramienta", "Herramienta")
                        .WithMany("CompraItems")
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Herramienta");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Herramienta", b =>
                {
                    b.HasOne("AppForSEII2526.API.Models.Fabricante", "Fabricante")
                        .WithMany("Herramienta")
                        .HasForeignKey("Fabricanteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fabricante");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.OfertaItem", b =>
                {
                    b.HasOne("AppForSEII2526.API.Models.Herramienta", "herramienta")
                        .WithMany("OfertaItems")
                        .HasForeignKey("herramientaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppForSEII2526.API.Models.Oferta", "oferta")
                        .WithMany("OfertaItems")
                        .HasForeignKey("ofertaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("herramienta");

                    b.Navigation("oferta");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.ReparacionItem", b =>
                {
                    b.HasOne("AppForSEII2526.API.Models.Herramienta", "Herramienta")
                        .WithMany("ReparacionItems")
                        .HasForeignKey("HerramientaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppForSEII2526.API.Models.Reparacion", "Reparacion")
                        .WithMany("ReparacionItems")
                        .HasForeignKey("ReparacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herramienta");

                    b.Navigation("Reparacion");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Alquiler", b =>
                {
                    b.Navigation("AlquilarItems");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Compra", b =>
                {
                    b.Navigation("CompraItems");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Fabricante", b =>
                {
                    b.Navigation("Herramienta");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Herramienta", b =>
                {
                    b.Navigation("AlquilarItems");

                    b.Navigation("CompraItems");

                    b.Navigation("OfertaItems");

                    b.Navigation("ReparacionItems");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Oferta", b =>
                {
                    b.Navigation("OfertaItems");
                });

            modelBuilder.Entity("AppForSEII2526.API.Models.Reparacion", b =>
                {
                    b.Navigation("ReparacionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
